name: Cypress Tests

on:  
  push:  
    branches: main
  pull_request:  
    branches: main 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Node initialize
        run: npm init
        
      - name: Clean cache
        run: npm cache clean --force

      - name: Remove package lock
        run: rm -rf node_modules package-lock.json
             
      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm record-run
          wait-on: 'http://localhost:3000'
          browser: chrome
